"""
Lookup for Dashboard page object. change
"""
from .base import Locator


DASHBOARD_LOOKUP = {
    "account_settings": Locator("css selector", "a[href*='details']"),
    "edit_password": Locator("id", "edit-password-link"),
    "old_pass_field": Locator("id", "member-existing-password"),
    "new_pass_field": Locator("id", "member-new-password"),
    "confirm_pass_field": Locator("id", "member-confirm-password"),
    "submit_new_password": Locator("id", "save-member-password"),
    "member_firstname": Locator("id", "member-first-name"),
    "member_lastname": Locator("id", "member-last-name"),
    "submit_new_details": Locator("id", "save-member-details"),
    "update_success": Locator("css selector", ".message-success"),
    "updated_email": Locator("css selector", ".member-email__value"),
    "first_last_name": Locator("css selector", "#member-name"),
    "day_field": Locator("css selector", "#member-day-of-birth"),
    "month_field": Locator("css selector", "#member-month-of-birth"),
    "year_field": Locator("css selector", "#member-year-of-birth"),
    "edit_email_link": Locator("id", "edit-email-link"),
    "email_field": Locator("id", "member-email"),
    "save_email_button": Locator("id", "save-member-email"),
    "edit_preferences_link": Locator("id", "edit-marketing-preferences-link"),
    "edit_preferences_check": Locator("id", "marketing-opt-in-label"),
    "yes_pref_but": Locator("id", "marketing-opt-in-label"),
    "no_pref_but": Locator("id", "marketing-opt-out-label"),
    "opt_in_post_button": Locator("id","marketing-opt-in-post-label"),
    "opt_in_email_button": Locator("id","marketing-opt-in-email-label"),
    "save_marketing_preferences": Locator("id", "save-marketing-preferences"),
    "report_lost_stolen": Locator("css selector", "a[href*='order-card']"),
    # "report_lost_stolen": Locator("css selector", ".order-replacement-card-link"),
    "next_button_at_order_new_card": Locator("css selector", ".btn-primary"),
    "edit_your_name_link": Locator("css selector", "#change-your-name"),
    "change_your_address_link": Locator("css selector", "#change-your-address"),
    "enter-address-manually": Locator("css selector", "#edit-address-manually"),
    "address_line1": Locator("css selector", "#address-line-1"),
    "address_line2": Locator("css selector", "#address-line-2"),
    "address_city": Locator("css selector", "#address-city"),
    "address_postcode": Locator("css selector", "#address-postcode"),
    "save_button": Locator("css selector", "#submit-button"),
    "save_address": Locator("css selector", "#submit-button"),
    "address_text": Locator("xpath", ".//*[@id='address-block']/p[1]"),
    "order_card_button": Locator("css selector", ".btn-primary.order-card__button"),
    "card_message": Locator("css selector", ".message"),
    "new_card_message": Locator("css selector", ".success-message"),
    "email_confirm": Locator("css selector", "#member-confirm-email"),
    "logout": Locator("xpath", "//input[@name='sign-out']"),
    "claim_receipt_link": Locator("css selector", "a[href*='claim-rewards']"),
    "till_no_field": Locator("css selector", "#till-id"),
    "store_no_field": Locator("css selector", "#store-id"),
    "dd_receipt_field": Locator("css selector", "#day-of-transaction"),
    "mm_receipt_field": Locator("css selector", "#month-of-transaction"),
    "yyyy_receipt_field": Locator("css selector", "#year-of-transaction"),
    "txn_receipt_field": Locator("css selector", "#transaction-id"),
    "salesforce_env_drop": Locator("css selector", "#oauth_env"),
    "salesforce_accept": Locator("css selector", "#termsAccepted"),
    "login_with_salesforce": Locator("css selector", "#loginBtn"),
    "salesforce_user": Locator("css selector","#username"),
    "salesforce_pass": Locator("css selector","#password"),
    "salesforce_login_button": Locator("css selector","#Login"),
    "salesforce_query": Locator("css selector", "#soql_query_textarea"),
    "query_submit": Locator("css selector", "[type=submit]"),
    "first_query_row": Locator("xpath", "((//table[@id='query_results']/tbody/tr)[2])/td[{}]"),
    "submit_txn": Locator("css selector", "#submit-transaction"),
    "x_balance": Locator("css selector", ".wallet-x-value"),
    "y_balance": Locator("css selector", ".wallet-y-value"),
    "invalid_date_receipt": Locator("css selector", ".sign-in-form__year-of-transaction-error.errors__field-error-message"),
    "edit_name_at_update_details": Locator("css selector", "#change-your-name"),
    "causes_link": Locator("css selector", "#causes-tile-link"),
    "card_number": Locator("css selector", ".memberdetails__card-number"),
    "register_success_message": Locator("css selector", "p.dashboard__success-message-text"),
    "current_cause_name":Locator("xpath", "//*[contains(text(),'Salford Loaves and Fishes Ltd')]"),
    "local_causes": Locator("id","local-causes"),
    "current_cause": Locator("id", "y-tile-cause-profile-link"),
    "change_cause": Locator("css selector", "a[href*='/causes']"),
    "select_new_cause": Locator("css selector", ".btn-primary"),
    "community_causes": Locator("xpath", ".// *[ @ id = 'local-causes']/div/div/a/div/h3[not(contains(text(),'backing'))]"),
    "historical_causes": Locator("css selector", "a[href*='/giving-history']"),
    "historical_causes_data": Locator("xpath", ".//*[@class='giving-history__table-container']"),
    "historical_cause_details": Locator("xpath", ".//*[@class='giving-history__table-body']/tr[1]/td[1]/a"),
    "home_page": Locator("css selector", "a[href*='/dashboard']")
}
