"""
Lookup for AdminSubnav page object. change
"""
from .base import Locator


REGISTRATION_PAGE_LOOKUP = {
    "member_title": Locator("css selector", "#member-title"),
    "first_name": Locator("css selector", "#member-first-name"),
    "last_name": Locator("css selector", "#member-last-name"),
    "employee_id": Locator("css selector", "#member-employee-number"),
    "day": Locator("css selector", "#member-day-of-birth"),
    "month": Locator("css selector", "#member-month-of-birth"),
    "year": Locator("css selector", "#member-year-of-birth"),
    "postcode": Locator("css selector", "#postcode"),
    "postcode_button": Locator("css selector", "#find-address-current"),
    "enter_address_manually": Locator("css selector", "#enter-address-manually"),
    "address_line_1": Locator("css selector", "#member-address-line-1"),
    "address_line_2": Locator("css selector", "#member-address-line-2"),
    "city": Locator("css selector", "#member-address-city"),
    "post_code": Locator("css selector", "#member-address-postcode"),
    "first_address_result": Locator("css selector", ".address-item:nth-child(1)"),
    "email": Locator("css selector", "#member-email"),
    "password": Locator("css selector", "#member-password"),
    "confirm_password": Locator("css selector", "#member-confirm-password"),
    "create_account": Locator("css selector", "#register-button"),
    "continue_button": Locator("css selector", ".btn-primary.btn-spaced"),
    "card_number": Locator("xpath", "//input"),
    "card_month": Locator("id", "expiry-month"),
    "card_year": Locator("id", "expiry-year"),
    "cvv_frame": Locator("css selector", ".gw-proxy-securityCode"),
    "cvv": Locator("xpath", "//input"),
    "submit_payment": Locator("css selector", "#submit-payment-form"),
    "success_message": Locator("css selector", ".success-message"),
    "membership_card_number": Locator("css selector", "#membership-card-number"),
    "reg_error_message": Locator("css selector", ".registration-error-message"),
    "reg_error_message_text": Locator("css selector", ".registration-error-message>p"),
    "link_card_no_field": Locator("id", "existing-member__membership-card-number"),
    "link_first_name_field": Locator("id", "first-name"),
    "link_last_name_field": Locator("id", "last-name"),
    "link_dd_field": Locator("id", "member-day-of-birth"),
    "link_mm_field": Locator("id", "member-month-of-birth"),
    "link_yyyy_field": Locator("id", "member-year-of-birth"),
    "link_account_button": Locator("css selector", ".link-account-button"),
    "link_account_email": Locator("id", "member-email"),
    "link_account_password": Locator("id", "member-password"),
    "link_account_confirm_password": Locator("id", "confirm-password"),
    "link_account_submit_credentials": Locator("css selector", ".btn-primary"),
    "age_error": Locator("css selector", ".member-registration-error-message__member-year-of-birth-error.errors__field-error-message"),
    "confirm_email": Locator("css selector", "#member-confirm-email"),
    "confirm_account_email": Locator("css selector", "#member-confirm-email"),
    "address_1_error": Locator("css selector", "[data-parsley-error-message='Error, enter the first line of your address']"),
    "year_error": Locator("xpath", "//li[@class='parsley-required'][contains(text(),'Please enter your date of birth (DD/MM/YYYY)')]"),
    "email_error": Locator("xpath", "//li[@class='parsley-custom-error-message'][contains(text(),'Please enter a valid email address (example: name@mail.com)')]"),
    "log_out": Locator("xpath", "//input[@name='sign-out']"),
    "username_field": Locator("id", "verify-member-email"),
    "verify_email_button": Locator("css selector", ".verify-email-button"),
    "initial_card_number": Locator("css selector", "#member-card-number"),
    "verify_card_button": Locator("css selector", "#register-check-card-button"),
    "card_number_iframe": Locator("css selector", ".gw-proxy-number"),
    "card_option": Locator("id", "payment-option-card"),
    # "card_option": Locator("css selector", "#payment-option-card"),
    "no_key_fob": Locator("css selector", ".register-check-card__member-has-card--no"),
    "yes_key_fob": Locator("css selector", ".register-check-card__member-has-card--yes"),
    "error_at_failed_identity": Locator("css selector", ".errors-serverside"),
    "card_number_field": Locator("id", "member-card-number"),
    "yes_button_at_linked_account": Locator("id", "member-has-card-yes"),

}